[tool.poetry]
name = "wildcatter"
version = "0.0.1"
description = "Reinforcement learning framework for well placement and optimization"
authors = ["Altay Sansal <tasansal@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
gym = {version = "^0.23.1", extras = ["nomujoco"]}
pygame = "^2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
