[tool.poetry]
name = "wildcatter"
version = "0.1.0"
description = "Reinforcement learning framework for well placement and optimization"
authors = ["Altay Sansal <tasansal@users.noreply.github.com>"]
license = "MIT"


[tool.poetry.dependencies]
python = ">=3.9 <3.11"
gym = "~=0.21"
pygame = "^2.1.2"
ray = {version = "^1.13.0", extras = ["rllib"]}
torch = "^1.11.0"

[tool.poetry.group.notebook]
optional = true

[tool.poetry.group.notebook.dependencies]
matplotlib = "^3.5.2"
jupyterlab = "^3.4.3"

[tool.poetry.group.serve]
optional = true

[tool.poetry.group.serve.dependencies]
pygbag = "^0.0.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.1.0b2"]
build-backend = "poetry.core.masonry.api"
