[tool.poetry]
name = "wildcatter"
version = "0.0.1"
description = "Wildcatter"
authors = ["Altay Sansal <tasansal@users.noreply.github.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/GeoML-SIG/wildcatter"
repository = "https://github.com/GeoML-SIG/wildcatter"
documentation = "https://wildcatter.readthedocs.io"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
]

[tool.poetry.urls]
Changelog = "https://github.com/tasansal/wildcatter/releases"

[tool.poetry.dependencies]
python = ">=3.8 <3.11"
gym = "^0.21"
pygame = "^2.1.2"
ray = {version = "^1.13.0", extras = ["rllib"]}
torch = "^1.12.0"

[tool.poetry.group.notebook]
optional = true

[tool.poetry.group.notebook.dependencies]
matplotlib = "^3.5.2"
jupyterlab = "^3.4.3"

[tool.poetry.group.serve]
optional = true

[tool.poetry.group.serve.dependencies]
pygbag = "^0.0.9"

[tool.poetry.group.dev.dependencies]
black = {version = "^22.6.0", extras = ["jupyter"]}
isort = "^5.10.1"

[tool.poetry.scripts]
wildcatter = "wildcatter.__main__:main"

[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = 2

[build-system]
requires = ["poetry-core>=1.1.0b2"]
build-backend = "poetry.core.masonry.api"
